### ISSUE TITLE
Prep for broader release

### ISSUE THREAD

**Issue by ctgraham** [bryklaus/glpc_related-entries#22]
I'm updating the README and docker-compose.yml to provide general instructions for use.  One of the changes will be to rename the mysql bind mount from "glpc-mysql-data" to just "mysql-data" which may impact any existing dev instances you have, so I'm formulating this as a PR rather than a direct commit.

**Comment by bryklaus** [comment]
I have no existing dev instances, so I'm going to go ahead and merge the pull request and close.
