### ISSUE TITLE
Hide crossreferences block on the front end if no crossreferences are present

### ISSUE THREAD

**Issue by ctgraham** [bryklaus/glpc_related-entries#24]
@bryklaus writes:
> The only minor tweak that might be considered would be to modify /app/src/static/js/crossRefBlock.js so that the Cross Ref block doesn’t display if there are no cross reference entries, to prevent something like this from happening
![image](https://github.com/bryklaus/glpc_related-entries/assets/7001322/68e5e08f-c1b6-4aee-a728-307b58f203c6)

**Comment by ctgraham** [comment]
Actually this causes a downstream error:
`Error: TypeError: result is null`

Triggered:
https://github.com/bryklaus/glpc_related-entries/blob/34323f7964aa233ca52e941ef4e5636ffd07cbc3/app/src/static/js/crossRefBlock.js#L152

Caught:
https://github.com/bryklaus/glpc_related-entries/blob/34323f7964aa233ca52e941ef4e5636ffd07cbc3/app/src/static/js/crossRefBlock.js#L160

**Comment by bryklaus** [comment]
I think the following code should resolve the downstream error:

```
if (result.list) { // Check if result.list is not null
   relatedEntriesDiv.appendChild(result.list);
}
```

**Comment by bryklaus** [comment]
> I think the following code should resolve the downstream error:
> 
> ```
> if (result.list) { // Check if result.list is not null
>    relatedEntriesDiv.appendChild(result.list);
> }
> ```

Although, now that I think about it, I'm not sure this will prevent the rest of the Cross Ref Block from displaying.
