### ISSUE TITLE
Proposal: Cross Reference Custom Block (Front-End)

### ISSUE THREAD

**Issue by bryklaus** [bryklaus/glpc_related-entries#30]
Following up on the e-mail conversation, I propose to modify `app/src/static/js/crossRefBlock.js` so that, rather than identifying the hard-coded `parentElement` on the galley page and inserting the Cross Reference Block beneath it using `.insertAdjacentElement`, we use the OJS Custom Block Manager plugin to allow journal managers to create a custom block whose content will be dynamically replaced with the cross references.

This means we'll remove the `titleSpan` part of the code (journal managers can give the block its own name). The class name will also be provided by managers in the `.env` file, maybe in a separate section called "Frontend Config" using the variable `BLOCK_NAME`, which we'll also have to add to `docker-compose.yml`.

If that all sounds good, I'll go ahead and implement the changes tomorrow.

**Comment by ctgraham** [comment]
There is one problem to our strategy here.  Custom Blocks can't be restricted to only Article pages.  The Inline HTML Galley Sidebar blocks appear only on Articles, but other Custom Blocks, like "links", render on every page.

Some options, each a little hack-ish:

* Move back to targeting an existing block, and cloning a new block underneath it.
  * (+) Code was already in place and working
  * (+) Can easily target an Inline HTML Galley Sidebar Block, so this is only effective on Articles.
  * (-) Need to replicate HTML structure and content into the JS which conceptually ought to be in the application
  * (-) Would need to consider the "not-found" condition to be normal, so harder to error trap legitimate problems in display
* Render an empty custom block everywhere, and hide it with CSS on non-article pages
  * (+) Straightforward CSS query
  * (-) Ugly need for a CSS hide
  * (+) Keeps the HTML structure and content in the app, not the JS
* Other?

**Comment by bryklaus** [comment]
Shoot, I forgot that the regular custom blocks show up everywhere. I never liked the fact that `crossRefBlock.js` is doing all of this HTML rendering, but hiding/showing the block using CSS feels even hackier. I'd be inclined to stick with option 1, especially since the code is already in place. Frankly, it probably makes it easier for other hypothetical journal managers, too, since it means they don't need to figure out what the CSS id is for the Custom Block they create using the Custom Block Manager. Instead, they can just specify whatever value they want in `.env` and it'll just work.

**Comment by bryklaus** [comment]
I just updated the pull request. I reverted the changes to `crossRefblock.js`, but I also added two new environmental variables: in addition to `BLOCK_CLASS_NAME` (formerly `BLOCK_NAME`) I added `BLOCK_CLASS_TARGET` and `BLOCK_TITLE`. Journal managers now have the option to target any block they want (i.e., any block beneath which the Cross References block will appear) and to give the Cross References block any title they want.

I've specified default values for all three in `env.template` and `docker-compose.yml`, although I'm not sure if you think that makes sense or not. Happy to remove the defaults if you think it's better to keep the values empty.

**Comment by bryklaus** [comment]
> I just updated the pull request. I reverted the changes to `crossRefblock.js`, but I also added two new environmental variables: in addition to `BLOCK_CLASS_NAME` (formerly `BLOCK_NAME`) I added `BLOCK_CLASS_TARGET` and `BLOCK_TITLE`. Journal managers now have the option to target any block they want (i.e., any block beneath which the Cross References block will appear) and to give the Cross References block any title they want.
> 
> I've specified default values for all three in `env.template` and `docker-compose.yml`, although I'm not sure if you think that makes sense or not. Happy to remove the defaults if you think it's better to keep the values empty.

Perhaps BLOCK_CLASS_NAME isn't even necessary.

**Comment by ctgraham** [comment]
Resolved by #31 

Dev and prod have been updated and redeployed with the default values.
