### ISSUE TITLE
Reference mysql user password

### ISSUE THREAD

**Issue by ctgraham** [bryklaus/glpc_related-entries#4]
This
https://github.com/bryklaus/glpc_related-entries/blob/f8c7b379eb2321c5f9efe69c3c15eda77924839a/app/docker-compose.yml#L32C30-L32C30

Should reference this:
https://github.com/bryklaus/glpc_related-entries/blob/f8c7b379eb2321c5f9efe69c3c15eda77924839a/app/env.template#L10

Not the root password.

**Comment by bryklaus** [comment]
Yes. That's also the case for line 19 in docker-compose.yml, no? I changed both in the latest pull request but can go back to change it if that's not right.

**Comment by ctgraham** [comment]
Yes, https://github.com/bryklaus/glpc_related-entries/pull/10 looks right to me.
