### ISSUE TITLE
Is the internal node server production ready?

### ISSUE THREAD

**Issue by ctgraham** [bryklaus/glpc_related-entries#5]
The Dockerfile runs `node src/index.js`
https://github.com/bryklaus/glpc_related-entries/blob/f8c7b379eb2321c5f9efe69c3c15eda77924839a/app/Dockerfile#L11

And so does the docker-compose:
https://github.com/bryklaus/glpc_related-entries/blob/f8c7b379eb2321c5f9efe69c3c15eda77924839a/app/docker-compose.yml#L5

Is the `node` executable production ready, or does it need any additional config for hardening?

Is the second run needed?

**Comment by bryklaus** [comment]
I believe the second command is not necessary; the node executable should be production ready.
