### ISSUE TITLE
Hardcoded section id?

### ISSUE THREAD

**Issue by ctgraham** [bryklaus/glpc_related-entries#6]
Is this a hardcoded OJS section id?

https://github.com/bryklaus/glpc_related-entries/blob/f8c7b379eb2321c5f9efe69c3c15eda77924839a/app/src/static/js/relatedEntries.js#L291C3-L291C3

If so, we may want to abstract it.

**Comment by bryklaus** [comment]
Yes, you're right. This is our "Entries" section ("Front Matter" is the other). Since this is in the public-facing JS, and so it can't easily access environmental variables, how would you recommend abstracting it?

**Comment by ctgraham** [comment]
I'm linking this to my comment here: https://github.com/bryklaus/glpc_related-entries/pull/3#pullrequestreview-1511746450 for my own reference; the solutions should be cross-pollinating.
