### ISSUE TITLE
Define some magic numbers

### ISSUE THREAD

**Issue by ctgraham** [bryklaus/glpc_related-entries#7]
https://github.com/bryklaus/glpc_related-entries/blob/f8c7b379eb2321c5f9efe69c3c15eda77924839a/app/src/static/js/relatedEntries.js#L496

Can we name this as JS constants, with a link to the OJS constants?
https://github.com/pkp/pkp-lib/blob/e8ebfba18f5fb809cc5c43329c3442d6ca3d44e1/classes/submission/PKPSubmission.php#L42-L45

**Comment by bryklaus** [comment]
Sure, that would definitely make the code clearer. Just something like this?

```
const STATUS_QUEUED = 1;
const STATUS_PUBLISHED = 3;
const STATUS_DECLINED = 4;
const STATUS_SCHEDULED = 5;

if (publicationStatus === STATUS_PUBLISHED || publicationStatus === STATUS_SCHEDULED) {
  // ...
}

```
