### ISSUE TITLE
Is the first publication, english title, what we really want?

### ISSUE THREAD

**Issue by ctgraham** [bryklaus/glpc_related-entries#8]
https://github.com/bryklaus/glpc_related-entries/blob/f8c7b379eb2321c5f9efe69c3c15eda77924839a/app/src/routes/data.js#L45-L46

This appears to hard code assumptions of the first published version, and the English title.  Should this be generalized to the "current" published version and the primary language title (or user's language title)?

**Comment by bryklaus** [comment]
Yes on both counts. I had trouble extracting the contents of the title from the OJS JSON file until I used fullTitle.en_US, but before launching the script that should not be a built-in assumption.

**Comment by bryklaus** [comment]
I just realized that the data.js route still has code in it that isn't language agnostic for getting titles, will need to update it. I think the same solution as in the other part of the code in data.js can be used to fix it. https://github.com/bryklaus/glpc_related-entries/blob/bed2e2339b184b73397ce484a04498744d6628cb/app/src/routes/data.js#L107C1-L123C6

**Comment by bryklaus** [comment]
The above issue should be resolved by #19
